import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import TopNav from "@/components/TopNav";
import { FloatingNav } from "@/components/ui/Floating-NavBar";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Eden International",
  description: "Generated by create next app",
  icons: {
    icon: '/icon.png', // /public path
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TopNav />
        <FloatingNav />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
